import { Category } from "./interface";

export enum CategoriesType {
  animals = 'Animals',
  nature = 'Nature',
  food = 'Food',
  cityPlaces = 'City Places',
  hobby = 'Hobby',
  school = 'School',
  clothes = 'Clothes',
  faceAndBody = 'Face And Body',
  sports = 'Sports',
  fruits = 'Fruits',
  vegetables = 'Vegetables',
  random = 'Random',
}

export const ANIMALS: Category[] = [
  {
    level: 1,
    words: "GORILLA,RABBIT,HORSE,GOAT,DOG,SHEEP,GIRAFFE,LION,PANDA,BEAR,ELEPHANT,PARROT,EAGLE,DUCK,CHICKEN,CAT,GOOSE,COW,BIRD,TIGER",
  },
  {
    level: 2,
    words: "CROW,PIGEON,SPARROW,PENGUIN,MONKEY,CAMEL,LEOPARD,LLAMA,WALRUS,RHINO,WOLF,ZEBRA,KANGAROO,DONKEY,HIPPOPOTAMUS,FROG,TOAD,SPIDER,CROW,DOLPHIN",
  },
  {
    level: 3,
    words: "HAWK,CHEETAH,HYENA,SWALLOW,ALLIGATOR,RHINOCEROS,ARMADILLO,REINDEER,SQUIRREL,BADGER,LIZARD,CHIMPANZEE,WHALE,FLAMINGO,COYOTE,FALCON,SEAGULL,PEACOCK,OTTER,TADPOLE",
  }
];

export const NATURE: Category[] = [
  {
    level: 1,
    words: "BUSH,SAND,POND,RIVER,LAKE,PLANET,STAR,WATER,TREE,CAVE,STONE,MUD,FOREST,RAINBOW,CLOUD,SNOW,SNOWFLAKE,SPACE,SUN,ROSE,SUNFLOWER",
  },
  {
    level: 2,
    words: "FLOWER,MINE,VOLCANO,PLANT,BEACH,OCEAN,ISLAND,MOUNTAIN,LEAF,DESERT,TORNADO,AUTUMN,WINTER,SUMMER,SPRING,ICEBERG,WATERFALL,GARDEN,GRASS,MOON",
  },
  {
    level: 3,
    words: "MUSHROOM,PEBBLE,MOSS,ENVIRONMENT,ECOLOGY,POLLUTION,POISON,PROTECT,RIVERBANK,CLIFF,FIELD,LIGHTNING,FLOOD,EARTHQUAKE,AVALANCHE,DAWN,TWILIGHT,LANDSCAPE,MEADOW,SCENERY",
  }
];

export const FOOD: Category[] = [
  {
    level: 1,
    words: "PIZZA,CHICKEN,BREAD,TOMATO,POTATO,BANANA,APPLE,CHEESE,MEAT,BISCUIT,ICE CREAM,BUTTER,BISCUIT,HOTDOG,PASTA,COFFEE,MILK,TOAST,JUICE,CAKE,CANDY",
  },
  {
    level: 2,
    words: "CORNFLAKES,HAMBURGER,AVOCADO,SANDWICH,WAFFLE,CHOCOLATE,MILKSHAKE,SALAD,ONION,WATERMELON,SEAFOOD,GRAPES,DONUT,DESSERT,FRIES,CRISPS,RICE,CARROTS,PASTA,KETCHUP,TUNA",
  },
  {
    level: 3,
    words: "CEREALS,MUSSELS,CROISSANT,CRUNCHY,PRETZEL,OMELETTE,BAGUETTE,LETTUCE,EGGPLANT,YOGHOURT,STRAWBERRY,CRACKER,NOODLES,CHEESEBURGER,LEMONADE,CHIPS,ROASTED,BAKED,VANILLA,CINNAMON",
  }
];

export const CITY_PLACES: Category[] = [
  {
    level: 1,
    words: "BANK,HOSPITAL,SCHOOL,PLAYGROUND,HOTEL,CAFE,SHOP,HOUSE,TOWER,FARM,VILLAGE,CITY,TOWN,AIRPORT,STREET,CAPITAL,PALACE,CASTLE,BRIDGE,PARK",
  },
  {
    level: 2,
    words: "RESTAURANT,BOWLING,PARKING,FLORIST,BUS STATION,SKYSCRAPER,APARTMENT,PHARMACY,CHURCH,BOOKSTORE,LIBRARY,GREENGROCERY,SUPERMARKET,CINEMA,THEATRE,MUSEUM,STADIUM,SIGHTSEEINGS,STATION,LAWN",
  },
  {
    level: 3,
    words: "AMUSEMENT PARK,FACTORY,CROSSROADS,MARKET,BAKERY,MOSQUE,COURT,AQUARIUM,CATHEDRAL,UNDERGROUND,PARLIAMENT,OBSERVATORY,ROUNDABOUT,PEDESTRIAN,CROSSING,PAVEMENT,MEGACITY,BOOKSTORE,CYCLE PATH,TELEPHONE BOX",
  }
];

export const HOBBY: Category[] = [
  {
    level: 1,
    words: "DRAWING,PAINTING,READING,DANCING,CHESS,MUSIC,SINGING,WRITING,COOKING,FISHING,SKIING,SKATING,FOOTBALL,HOCKEY,ORIGAMI,HOBBY,COMPUTER GAMES,GUITAR,VIOLIN,DRUMS",
  },
  {
    level: 2,
    words: "PHOTOGRAPHY,GARDENING,HUNTING,COLLECTING,KNITTING,GRAFFITI,TOURISM,YOGA,CAMPING,HIKING,BLOGGING,SHOPPING,PROGRAMMING,KARATE,TENNIS,COOKING,WATCHING FILMS,PLAYING THE GUITAR,PLAYING DRUMS,PLAYING INSTRUMENTS",
  },
  {
    level: 3,
    words: "POTTERY,CARVING,CALLIGRAPHY,HANDICRAFT,ASTROLOGY,BEADING,JOGGING,FLORICULTURE,NEEDLEWORK,HERBARIUM,ARCHAEOLOGY,EMBROIDERY,WOODBURNING,PHILATELY,PARKOUR,SURFING THE NET,LANGUAGE LEARNING,SELF-EDUCATION,BOARD GAMES,MODELLING",
  }
];

export const SCHOOL: Category[] = [
  {
    level: 1,
    words: "CLASSROOM,BOOK,PENCIL,COPYBOOK,COMPUTER,DESK,CHAIR,CLOCK,PAINT,RULER,PAPER,SCHOOLBAG,MATHS,BOARD,MARKER,PEN,PENCIL CASE,PALETTE,CLAY,SCHOOLYARD,ENGLISH,HISTORY,BIOLOGY",
  },
  {
    level: 2,
    words: "SCISSORS,CHALK,SHARPENER,RUBBER,GLOBE,POSTER,LITERATURE,TEACHER,PAINTBRUSH,CALCULATOR,NOTEBOOK,BOOKCASE,BACKPACK,MICROSCOPE,TABLET,PRIMARY SCHOOL,LYCEUM,COLLEGE,PHYSICS,SCIENCE,STAFF ROOM",
  },
  {
    level: 3,
    words: "COMPREHENSIVE SCHOOL,GYMNASIUM,CANTEEN,WORKSHOP,HEADMASTER,LABORATORY,LIBRARIAN,TIMETABLE,CURRICULUM,CHEMISTRY,EDUCATION,STAPLER,CRAYON,CHALKBOARD,PAPERCLIP,RECREATION,ASSEMBLY HALL,ENTRANCE HALL,FORM MISTRESS,SECURITY GUARD",
  }
];

export const CLOTHES: Category[] = [
  {
    level: 1,
    words: "SHIRT,SHOES,BOOTS,PANTS,SOCKS,COAT,DRESS,JEANS,SHORTS,HAT,T-SHIRT,GLASSES,CAP,BELT,BAG,BUTTON,BOW,TIGHTS,RING,TIE",
  },
  {
    level: 2,
    words: "SUIT,TROUSERS,JUMPER,PANTS,SKIRT,BLOUSE,LEGGINGS,RAINCOAT,MITTENS,SWIMSUIT,SUNGLASSES,SWEATER,HOODIE,UNIFORM,CARDIGAN,LACES,HIGH HEELS,TRAINERS,VEST,APRON,BOW TIE",
  },
  {
    level: 3,
    words: "BATHROBE,PYJAMAS,SCARF,UNDERWEAR,JACKET,GLOVES,TRACKSUIT,LEOTARD,WINDBREAKER,BOMBER,OVERALL,SANDALS,SLIPPERS,COLLAR,NIGHTGOWN ,ANORAK,RAIN BOOTS,ZIPPER,WALLET,POCKET",
  }
];

export const FACE_AND_BODY: Category[] = [
  {
    level: 1,
    words: "FEET,NECK,HANDS,HEAD,LEGS,EYES,EARS,MOUTH,NOSE,HAIR,CHIN,JAW,TEETH,BACK,KNEE,HIPS,NAIL,HEART,SKIN,TOES,THIGH",
  },
  {
    level: 2,
    words: "CHEST,KNEES,FINGERS,TOES,STOMACH,EYEBROW,CHEEKS,TOOTH,FOREHEAD,LIPS,PALM,THUMB,BELLY,HEEL,KNEES,CALF,SHIN,MOLE,LITTLE FINGER,CUTICLE",
  },
  {
    level: 3,
    words: "WRIST,ELBOW,SHOULDER,ANKLES,WAIST,BEARD,MOUSTACHE,NOSTRILS,TONGUE,DIMPLES,EYELASHES,FIST,TOENAIL,NAVEL,FOREARM,CHEEKBONES,EARLOBE,EYELID,FRECKLE,SCAR,SKELETON",
  }
];

export const SPORTS: Category[] = [
  {
    level: 1,
    words: "BOXING,FOOTBALL,HOCKEY,VOLLEYBALL,GYMNASTICS,RUNNING,KARATE,DANCING,JUDO,SWIMMING,DIVING,SKATING,SKIING,SKATEBOARD,ROLLER,SPORTSMAN,SPORTS SCHOOL,DO SPORTS,FOOTBALL PLAYER,MATCH",
  },
  {
    level: 2,
    words: "CYCLING,ATHLETICS,YACHTING,SHOOTING,SNOWBOARD,HORSE RACING,BILLIARD,ACROBATICS,BADMINTON,BASKETBALL,TENNIS,CLIMBING,WINDSURFING,CRICKET,RUGBY,COMPETITION,DO TRAINING,STADIUM,SPORTS GROUND,SWIMMING POOL",
  },
  {
    level: 3,
    words: "ROWING,ARCHERY,STEEPLECHASE,GLIDING,KAYAKING,MOUNTAINEERING,WRESTLING,CURLING,SOCCER,SQUASH,TRAMPOLINING,WEIGHT LIFTING,SCOREBOARD,SCUBA,SLEDDER,KNOCKOUT,WINTER,OLYMPIC,DECATHLON,MARATHON",
  }
];

export const FRUITS: Category[] = [
  {
    level: 1,
    words: "BANANA,APPLE,WATERMELON,MELON,CHERRY,GRAPE,ORANGE,MANGO,PEACH,PEAR,KIWI,LEMON,PLUM,FIG,POMELO,COCONUT,AVOCADO,BREADFRUIT,BLUEBERRIES,CURRANT",
  },
  {
    level: 2,
    words: "STRAWBERRY,PINEAPPLE,PAPAYA,COCONUT,GRAPEFRUIT,RASPBERRY,AVOCADO,LIME,APRICOT,BLUEBERRY,NECTARINE,BLACKCURRANT,TANGERINE,JACKFRUIT,LYCHEE,CANTALOUPE,MANGOSTEEN,RAISINS,MANDARIN,TROPICAL FRUIT",
  },
  {
    level: 3,
    words: "POMEGRANATE,CARAMBOLA,GUAVA,GOOSEBERRY,CRANBERRY,DURIAN,DRAGON FRUIT,MULBERRY,PERSIMMON,ELDERBERRY,SAPODILLA,PHYSALIS,DATE,RAMBUTAN,KIWIFRUIT,PASSION FRUIT,BOYSENBERRY,CITRON,HONEYDEW,KUMQUAT",
  }
];

export const VEGETABLES: Category[] = [
  {
    level: 1,
    words: "ONION,TOMATO,POTATO,CORN,CHILLI,BROCCOLI,RADISH,CARROT,CUCUMBER,PEAS,BEAN,PEPPER,CABBAGE,BEET,PUMPKIN,VEGETABLE,BELL PEPPER,CELERY,SWEET POTATO,AVOCADO",
  },
  {
    level: 2,
    words: "CABBAGE,SPINACH,MUSHROOM,LETTUCE,EGGPLANT,ARTICHOKE,CELERY,GARLIC,OLIVE,TURNIP,LEEK,PARSLEY,CUCUMBER,POTATO,BEETROOT,SALAD VEGETABLE,VEGETABLE,RED ONION,YELLOW ONION",
  },
  {
    level: 3,
    words: "ASPARAGUS,CAULIFLOWER,ZUCCHINI,BRUSSELS SPROUT,FENNEL,SQUASH,PARSNIPS,BEETROOT,BUTTERNUT,ICEBERG,CHARD,DILL,CHICKPEAS,HORSERADISH,SPINACH,STRING BEANS,YAM,BULB,GREENS,LEAF VEGETABLE",
  }
];

export const RANDOM: Category[] = [
  {
    level: 1,
    words: "FAMILY,FRIEND,FLOWER,FOREST,COUNTRY,INSECT,SPIDER,WORLD,AUNT,UNCLE,WOMAN,HUSBAND,PHONE,PLACE,MARKET,WEEKEND,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY",
  },
  {
    level: 2,
    words: "WIND,WEST,EAST,NORTH,DICTIONARY,PERSON,EVENING,MORNING,ANIMAL,MOTHER,DAUGHTER,CHILDREN,ECOLOGICAL,NEPHEW,COUSIN,RELATIVES,HAPPINESS,QUESTION,COMMUNICATION,DIALOGUE,UNIVERSITY,TICKET,PASSPORT,LAWYER",
  },
  {
    level: 3,
    words: "ADDICTION,AMBIVALENCE,CONFIDENCE,EVIDENCE,CIRCUMSTANCE,ADHERENCE,ATTRACTIVENESS,ISOLATION,TREATMENT,IMPROVEMENT,SUSPICIOUSNESS,RESPONSIBILITY,MISUNDERSTANDING,DOWNFALL,DESTINATION,MEANINGFUL,REMARKABLE,ASTONISHING,CONTEMPORARY,UNDERSTANDABLE",
  }
];
